ideas/config/routes.rb
Ideas::Engine.routes.draw do
  resources :items
  root 'items#index'
end

ideas/app/models/ideas/application_record.rb
module Ideas
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

ideas/app/models/ideas/item.rb
module Ideas
  class Item < ApplicationRecord
  end
end

ideas/app/controllers/ideas/application_controller.rb
module Ideas
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception
  end
end

ideas/app/controllers/ideas/items_controller.rb
require_dependency "ideas/application_controller"

module Ideas
  class ItemsController < ApplicationController
    before_action :set_item, only: [:show, :edit, :update, :destroy]

    # GET /items
    def index
      @items = Item.all
    end

    # GET /items/1
    def show
    end

    # GET /items/new
    def new
      @item = Item.new
    end

    # GET /items/1/edit
    def edit
    end

    # POST /items
    def create
      @item = Item.new(item_params)

      if @item.save
        redirect_to @item, notice: 'Item was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /items/1
    def update
      if @item.update(item_params)
        redirect_to @item, notice: 'Item was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /items/1
    def destroy
      @item.destroy
      redirect_to items_url, notice: 'Item was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_item
        @item = Item.find(params[:id])
      end

      # Only allow a trusted parameter "white list" through.
      def item_params
        params.require(:item).permit(:title, :content)
      end
  end
end

ideas/app/helpers/ideas/application_helper.rb
module Ideas
  module ApplicationHelper
  end
end

ideas/app/helpers/ideas/items_helper.rb
module Ideas
  module ItemsHelper
  end
end

ideas/app/views/ideas/items/_form.html.erb
<%= form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ideas/app/views/ideas/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

ideas/app/views/ideas/items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.content %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

ideas/app/views/ideas/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

ideas/app/views/ideas/items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @item.content %>
</p>

<%= link_to 'Edit', edit_item_path(@item) %> |
<%= link_to 'Back', items_path %>

ideas/app/views/layouts/ideas/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ideas</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    "ideas/application", media: "all" %>
</head>
<body>

<%= yield %>

</body>
</html>